### ISSUE TITLE
search channels is not working

### ISSUE THREAD

**Issue by ardumdev** [TwitchIO/TwitchIO#181]
Hi. I am new in python, and I would like to get streamers that stream gta. I know how to use search_categories, that one works for me, but search_channels is not.

it gives me this error:
```Traceback (most recent call last):
  File "\twitchio\client.py", line 176, in wrapped
    await func(*args)
  File "main.py", line 22, in event_ready
    await self.try_join_gta()
  File "main.py", line 35, in try_join_gta
    list_gta_players = await self.search_channels(query='gta', live_only=True)
  File "\twitchio\client.py", line 515, in search_channels
    return [SearchUser(self._http, x) for x in data]
  File "twitchio\client.py", line 515, in <listcomp>
    return [SearchUser(self._http, x) for x in data]
  File "twitchio\user.py", line 624, in __init__
    self.started_at = datetime.datetime.strptime(data["expires_at"], "%Y-%m-%dT%H:%M:%SZ") if self.live else None
KeyError: 'expires_at'
```

this is the code:

```
    async def try_join_gta(self):
        list_gta_players = await self.search_channels(query='gta', live_only=True)
```
I'm calling it in event_ready. (with await).

**Comment by EvieePy** [comment]
Should be fixed! Upgrade to the newest version by running `pip install -U twitchio`
👍

**Comment by ardumdev** [comment]
Yes, it works now. Thank you
