### ISSUE TITLE
client.start() is not working

### ISSUE THREAD

**Issue by chillymosh** [TwitchIO/TwitchIO#188]
When testing different methods of using client.start() it does not seem to work.

```
twitchbot = TwitchChatBot()
async def start():
    await twitchbot.start()

asyncio.run(start())
```
```
RuntimeError: Attempted to start a TwitchChatBot instance on a different loop than the one it was initialized with.
```

Trying to start it in it's own loop
```
twitchbot = TwitchChatBot()
async def start():
    await twitchbot.start()

loop = asyncio.get_event_loop()
twitchbot.loop.run_until_complete(start())
```
```
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<WSConnection._join_channel() done, defined at /usr/local/lib/python3.9/site-packages/twitchio/websocket.py:256> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/twitchio/websocket.py", line 258, in _join_channel
    await self.send(f"JOIN #{channel}\r\n")
  File "/usr/local/lib/python3.9/site-packages/twitchio/websocket.py", line 201, in send
    await self._websocket.send_str(message + "\r\n")
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_ws.py", line 150, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 687, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 598, in _send_frame
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fd53a3ba880>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fd53a3b2c40>, 7862350.675504461)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fd53a3ba8e0>
```
**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
Version: 2.0.5

**Comment by chillymosh** [comment]
The issue is self.start() needs self.connect() to run_forever otherwise it instantly hits finally: self.close()
The workaround for now is to just called self.connect() directly and handle cleanup yourself in a shutdown command self.close()

This will probably be something that waits till 3.0 to be fixed due to the design overhaul.
