### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by XuaTheGrate** [TwitchIO/TwitchIO#205]
New to the twitch api, encountered this error and a friend told me it shouldn't be possible. 
```py
Task exception was never retrieved
future: <Task finished name='Task-1' coro=<Client.connect() done, defined at G:\Programming\python\robomaya_twitch\.venv\lib\site-packages\twitchio\client.py:172> exception=KeyError('login')>
Traceback (most recent call last):
  File "G:\Programming\python\robomaya_twitch\.venv\lib\site-packages\twitchio\client.py", line 176, in connect
    await self._connection._connect()
  File "G:\Programming\python\robomaya_twitch\.venv\lib\site-packages\twitchio\websocket.py", line 128, in _connect
    self.nick = data["login"]
KeyError: 'login'
```
And relevant code:
```py
class RoboMaya(twitchio.Client):
    OAUTH_REFRESH_URL = "https://id.twitch.tv/oauth2/token"
    SCOPES = {
        "chat:read", "chat:edit"
    }
    CLIENT_ID = "..."
    CLIENT_SECRET = "..."

    def get_access_token(self) -> str:
        params = urlencode({"client_id": self.CLIENT_ID, "client_secret": self.CLIENT_SECRET, "grant_type": "client_credentials", "scope": " ".join(self.SCOPES)})
        data = requests.post(self.OAUTH_REFRESH_URL + "?" + params)
        data.raise_for_status()
        out = data.json()
        return out['access_token']

    def __init__(self):
        access_token = self.get_access_token()
        super().__init__(access_token, initial_channels=['...'])


if __name__ == '__main__':
    RoboMaya().run()
```

**Comment by chillymosh** [comment]
You do not need to do this at all, the lib handles the automatic refresh of the token. The process is all automated for token validation and refresh, you are skipping validation here and jumping straight to refresh which does not contain the necessary data.

**Comment by XuaTheGrate** [comment]
Thanks, the issue was I was using the wrong OAuth token.
