### ISSUE TITLE
SyntaxError on import in py3

### ISSUE THREAD

**Issue by Skippern** [TwitchIO/TwitchIO#29]
**Describe the bug**
SyntaxError exception thrown on `import twitchio` in Python3

**Are you using TwitchIO within a Discord Bot?**
No

**What commit of TwitchIO are you using?**
`pip show twitchio`
```
Metadata-Version: 1.1
Name: twitchio
Version: 0.0.3a206+ae55763
Summary: A python IRC and API wrapper for Twitch.
Home-page: https://github.com/EvieePy/TwitchIO
Author: EvieePy
Author-email: UNKNOWN
License: MIT
Location: /home/skippern/.local/lib/python3.5/site-packages
Requires: aiohttp, async-timeout, websockets
Classifiers:
  Development Status :: 2 - Beta
  License :: OSI Approved :: MIT License
  Intended Audience :: Developers
  Natural Language :: English
  Operating System :: OS Independent
  Programming Language :: Python :: 3.6
  Programming Language :: Python :: 3.7
  Topic :: Internet
  Topic :: Software Development :: Libraries
  Topic :: Software Development :: Libraries :: Python Modules
  Topic :: Utilities
```
**To Reproduce**
- Clone repository rewrite branch
- install with `python3 -m pip install -U .` when standing in repo directory
- run `python3` and `import twitchio`

**Expected behaviour**

**Screenshots**
```
python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import twitchio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/src/TwitchIO/twitchio/__init__.py", line 35, in <module>
    from .dataclasses import Context, Message, User, Channel
  File "/opt/src/TwitchIO/twitchio/dataclasses.py", line 32, in <module>
    from .abcs import Messageable
  File "/opt/src/TwitchIO/twitchio/abcs.py", line 99
    raise TwitchIOBException(f'IRC Message rate limit reached for channel <{channel}>.'
                                                                                      ^
SyntaxError: invalid syntax
>>> 
```
**(please complete the following information):**
 - OS: [Ubuntu 14.04]
 - Python: 3.6.3

**Comment by zaxutic** [comment]
You are not running Python 3.6.3. You are running Python 3.5.2, as seen in the output given when running `python3`. TwitchIO requires Python version 3.6 or higher. You need to update your version of Python to be able to use this library.
