### ISSUE TITLE
Issue with the lib handling the response from the edit

### ISSUE THREAD

**Issue by BadChromer** [TwitchIO/TwitchIO#383]
```client = twitchio.Client(token=USER_OAUTH_TOKEN, initial_channels=['CHANNEL_NAME'])
broadcaster = client.create_user(CHANNEL_ID, 'CHANNEL_NAME')


async def edit_reward(title: str, paused: bool, cost: int):
    main_reward = (await broadcaster.get_custom_rewards(token=USER_OAUTH_TOKEN, only_manageable=True))[0]
    await main_reward.edit(token=USER_OAUTH_TOKEN, title=title, paused=paused, cost=cost, max_per_user_per_stream=None)

async def main():
    await edit_reward(title='TEST', paused=False, cost=10)
    await client.start()

client.loop.run_until_complete(main())
```

So the code seems like working, but when i call

`await edit_reward(title='TEST', paused=False, cost=10)`

 It updates the reward and then throws TypeError:

> Traceback (most recent call last):
  File "c:\Users\user\Downloads\twitch_bot\twitch_bot.py", line 119, in <module>
    client.loop.run_until_complete(main())
  File "C:\Program Files\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "c:\Users\user\Downloads\twitch_bot\twitch_bot.py", line 100, in main
    print(await edit_reward(title='TEST', paused=True, cost=10))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\user\Downloads\twitch_bot\twitch_bot.py", line 34, in edit_reward
    await main_reward.edit(token=USER_OAUTH_TOKEN, title=title, paused=paused, cost=cost, max_per_user_per_stream=None)
  File "C:\Program Files\Python311\Lib\site-packages\twitchio\rewards.py", line 239, in edit
    for reward in data["data"]:                  ~~~~^^^^^^^^
TypeError: list indices must be integers or slices, not str

**Comment by IAmTomahawkx** [comment]
@BadChromer ive pushed a potential fix for this, can you try pulling from git and testing it?

**Comment by BadChromer** [comment]
@IAmTomahawkx Yeah, the fix helped. It's working fine now. Thank you.

**Comment by IAmTomahawkx** [comment]
Will close this with next release
